version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB:  ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - backend
    container_name: postgres

  redis:
    image: redis:latest
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD} # 這是一個 Redis 的環境變數例子
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - backend
    container_name: redis

networks:
  backend:
